---
- hosts: clin2
  become_method: sudo
  vars:
    ZFS_RPM_URL: http://download.zfsonlinux.org/epel/zfs-release.el8_2.noarch.rpm
  tasks:
    - name: Instal EPEL
      dnf:
        name: epel-release
        state: latest
      become: yes
    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest
      become: yes
    - name: Install openzfs repo
      dnf:
        name: "{{ ZFS_RPM_URL }}"
        state: latest
      become: yes
    - name: Install openzfs and dependencies
      dnf:
        name:
          - zfs
          - kernel-devel
        state: latest
      become: yes
