---
- hosts: clin2
  become_method: sudo
  tasks:
    - name: Instal EPEL
      dnf:
        name: epel-release
        state: latest
      become: yes
    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest
      become: yes
    - name: Install rclone
      dnf:
        name: rclone
        state: latest
      become: yes