---
  - hosts: clin2
    become_method: sudo
    vars:
      GROUP_LIST:
        - smb-homes
        - smb-general
        - cody
        - corinne
      ALL_USERS_GROUPS:
        - smb-homes
        - smb-general
      USER_LIST:
        - cody
        - corinne
      SHARE_DIRS: /data/zpool1/share/
    tasks:
      - name: Instal samba
        dnf:
          name: samba
          state: latest
        become: yes
      - name: Put smb config file in place.
        copy:
          src: smb.conf
          dest: /etc/samba/smb.conf
          owner: root
          group: root
          mode: "0644"
        become: yes
      - name: Create groups
        group:
          name: "{{ item }}"
        become: yes
        with_items: "{{ GROUP_LIST }}"
      - name: Create Users
        user:
          name: "{{ item }}"
          home: "{{ SHARE_DIRS }}/home/{{ item }}"
          create_home: yes
          shell: /sbin/nologin
          group: "{{ item }}"
          groups: "{{ ALL_USERS_GROUPS }}"
        become: yes
        with_items: "{{ USER_LIST }}"
      - name: Create general
        file: 
          path: "{{ SHARE_DIRS }}/general"
          state: directory
          owner: root
          group: smb-general
          mode: "2770"
        become: yes
      - name: Allow samba to modify files (SELinux)
        sefcontext:
          target: "{{ SHARE_DIRS }}(/.*)?"
          setype: samba_share_t
          state: present
        become: yes
      - name: Apply new SELinux file context to filesystem
        command: "restorecon -irv {{ SHARE_DIRS }}"
        become: yes
      - name: Enable/Restart smb
        service:
          name: smb
          state: restarted
          enabled: yes
        become: yes
      - name: Enable/Restart nmb
        service:
          name: nmb
          state: restarted
          enabled: yes
        become: yes
      - name: Enable smb through firewall
        firewalld:
          service: samba
          permanent: yes
          immediate: yes
          state: enabled
        become: yes
